import numpy as np
from disentanglement_utils import _discretize_latents, _calculate_mutual_information_matrix, _drop_constant_dims

EPS = 1e-12

# Based on paper:
#  > Suter, Raphael, Dorde Miladinović, Bernhard Schölkopf, and Stefan Bauer. 2019. “Robustly Disentangled Causal Mechanisms: Validating Deep Representations for Interventional Robustness.” arXiv:1811.00007. Preprint, arXiv, May 13. https://doi.org/10.48550/arXiv.1811.00007.
#  > Only special disentanglement case
# Largely generated by OpenAI ChatGPT 5.5 Thinking, checked for correctness by me, all comments written by me

def scalable_irs_score(gen_factors, latents):
    gen_factors = np.asarray(gen_factors)
    latents = np.asarray(latents, dtype=float)

    N, K = gen_factors.shape
    _, L = latents.shape

    # Normalizer per latent dim: max |z - mean(z)|
    max_deviations = np.max(np.abs(latents - latents.mean(axis=0)), axis=0)  # (L,)
    max_deviations = np.maximum(max_deviations, EPS)  # avoid divide-by-zero

    EMPIDA = np.zeros((L, K), dtype=float)

    for i in range(K):                                                  # For each generative factor
        uniq = np.unique(gen_factors[:, i])                             # unique values of g_i

        for val in uniq:
            match = (gen_factors[:, i] == val)

            if not np.any(match):
                continue

            e_loc = latents[match].mean(axis=0)                         # E[Z | g_i=val]
            diffs = np.abs(latents[match] - e_loc)                      # |Z - E[Z|g]|
            q = np.max(diffs, axis=0)
            EMPIDA[:, i] += q

        EMPIDA[:, i] /= max(len(uniq), 1)

    IRS_matrix = 1.0 - (EMPIDA / max_deviations[:, None])               # eq. 2 in og. paper

    disent_scores = IRS_matrix.max(axis=1)                              # eq. 3 in og. paper

    avg_score = float(np.average(disent_scores, weights=max_deviations)) # Weighted average by max_deviations to give more weight to latents with larger variation (more "capacity" to capture factors)

    return {
        "IRS": avg_score,
        "IRS_matrix": IRS_matrix,
        "disentanglement_scores": disent_scores,
        "EMPIDA": EMPIDA,
        "max_deviations": max_deviations,
    }

def compute_irs_from_multihot_labels(C, Z):
    Z = np.asarray(Z)
    Z = (Z > 0.5).astype(int)                                           # Ensure Z is binary (multihot)
    C_active = _drop_constant_dims(C)                                   # Remove constant latent dimensions

    if C_active.shape[1] == 0:                                          # No calculation needed if all latents are constant -> IRS=0 and empty matrix
        return {"IRS": 0.0, "IRS_matrix": np.zeros((0, Z.shape[1]))}

    return scalable_irs_score(Z, C_active) # Compute IRS

def compute_irs(C, Z):
    C_active = _drop_constant_dims(C)

    if C_active.shape[1] == 0:                                          # No calculation needed if all latents are constant -> IRS=0 and empty matrix
        return {"IRS": 0.0, "IRS_matrix": np.zeros((0, Z.shape[1]))}

    return scalable_irs_score(Z, C_active) # Compute IRS

def report_irs(irs_result, title="IRS"):
    print(f"{title} score: {irs_result['IRS']:.4f}")
    print("Per-latent disentanglement scores:", irs_result["disentanglement_scores"])
    print("Max deviations per latent:", irs_result["max_deviations"])