import numpy as np
import scipy as sp

from disentanglement_utils import _discretize_latents, _calculate_mutual_information_matrix, _drop_constant_dims

EPS = 1e-12

# Based on The paper:
#  > Chen, Ricky T. Q., Xuechen Li, Roger Grosse, and David Duvenaud. 2019. “Isolating Sources of Disentanglement in Variational Autoencoders.” arXiv:1802.04942. Preprint, arXiv, April 23. https://doi.org/10.48550/arXiv.1802.04942.
# Largely generated by OpenAI ChatGPT 5.5 Thinking, checked for correctness by me, all comments written by me

def scalable_mig_score(gen_factors, lat_codes):
    gen_factors = np.asarray(gen_factors)
    lat_codes = np.asarray(lat_codes, dtype=float)

    lat_codes_disc = _discretize_latents(lat_codes, num_bins=50)

    N, K = gen_factors.shape
    _, L = lat_codes_disc.shape


    mi_matrix = _calculate_mutual_information_matrix(gen_factors, lat_codes_disc)                   # 1.a Mutual Information matrix eq. 4.7 in literature review

    mig_matrix = np.zeros((L, K), dtype=float)
    factor_entropy = np.zeros(K, dtype=float)                                                       # 1.b Compute entropy of each factor to identify constant factors and for normalization
    for k in range(K):
        _, counts = np.unique(gen_factors[:, k], return_counts=True)
        probs = counts.astype(float) / counts.sum()
        factor_entropy[k] = sp.stats.entropy(probs)

    valid_factors = factor_entropy > EPS

    for k in range(K):                                                                              # 1.c Normalize MI by factor entropy to get MIG matrix, eq. 4.8
        if valid_factors[k]:
            mig_matrix[:, k] = mi_matrix[:, k] / factor_entropy[k]

    per_factor = np.zeros(K, dtype=float)                                                           # 2.  Make MIG matrix
    for k in range(K):
        if not valid_factors[k]:                                                                    # 2.  If factor k has zero entropy (constant), set per-factor MIG to 0 and skip (since it can't be captured by any latent)
            per_factor[k] = 0.0
            continue

        col = np.sort(mig_matrix[:, k])[::-1]

        if len(col) == 0:                                                                           # 2.b If no latent dimension has non-zero MIG for factor k, set per-factor MIG to 0
            per_factor[k] = 0.0
        elif len(col) == 1:                                                                         # 2.b If only one latent dimension has non-zero MIG for factor k, use that value directly (no second max)
            per_factor[k] = float(col[0])
        else:
            per_factor[k] = float(col[0] - col[1])                                                  # 2.b -- NORMAL CASE -- Max minus second max for factor k, eq. 4.8 before sum

    avg_mig = float(np.mean(per_factor))                                                            # 2.c Average only over known factors, eq. 4.8

    return {
        "MIG": avg_mig,
        "MIG_matrix": mig_matrix,
        "MI_matrix": mi_matrix,
        "per_factor": per_factor,
        "factor_entropy": factor_entropy,
        "valid_factors": valid_factors,
        "active_latents": L
        }


def compute_mig(C, Z):
    C_active = _drop_constant_dims(C)

    if C_active.shape[1] == 0:                                                                      # No calculation needed if all latents are constant -> MIG=0 and empty matrix
        K = Z.shape[1]

        return {
            "MIG": 0.0,
            "MIG_matrix": np.zeros((0, K), dtype=float),
            "MI_matrix": np.zeros((0, K), dtype=float),
            "per_factor": np.zeros(K, dtype=float),
            "factor_entropy": np.array([sp.stats.entropy(Z[:, k]) for k in range(K)]),
            "valid_factors": np.array(
                [sp.stats.entropy(Z[:, k]) > EPS for k in range(K)], dtype=bool
            ),
            "active_latents": 0,
        }

    return scalable_mig_score(Z, C_active)

def report_mig(mig_result: dict, title: str = "MIG"):
    print(f"{title} score: {mig_result['MIG']:.4f}")
    print("Per-factor MIG:", mig_result["per_factor"])
    print("Factor entropies:", mig_result["factor_entropy"])
    print("Valid factors:", mig_result["valid_factors"])
    print("Active latent dimensions:", mig_result["active_latents"])